use crate::config::Config;
use crate::error::Result;
use crate::pipeline::{StepResult, StepStatus};
use std::process::Command;
use std::time::Instant;

pub fn run(config: &Config, steps: &[StepResult]) -> Result<StepResult> {
    let start = Instant::now();

    // Check if PR already exists
    let existing = Command::new("gh")
        .args(["pr", "view", "--json", "url", "-q", ".url"])
        .output();

    match existing {
        Ok(output) if output.status.success() => {
            let url = String::from_utf8_lossy(&output.stdout).trim().to_string();
            // PR exists, update body
            let body = build_pr_body(config, steps);
            let _ = Command::new("gh")
                .args(["pr", "edit", "--body", &body])
                .output();

            return Ok(StepResult {
                name: "PR".into(),
                status: StepStatus::Pass,
                duration: start.elapsed(),
                output: Some(url),
            });
        }
        _ => {} // No existing PR, create new
    }

    // Check gh CLI exists
    let gh_check = Command::new("gh").arg("--version").output();
    if gh_check.is_err() || !gh_check.unwrap().status.success() {
        return Ok(StepResult {
            name: "PR".into(),
            status: StepStatus::Fail("gh CLI not found. Install: https://cli.github.com".into()),
            duration: start.elapsed(),
            output: None,
        });
    }

    let title = build_pr_title(config);
    let body = build_pr_body(config, steps);

    let mut args = vec![
        "pr".to_string(),
        "create".to_string(),
        "--title".to_string(),
        title,
        "--body".to_string(),
        body,
        "--base".to_string(),
        config.base_branch.clone(),
    ];

    if config.pr.draft {
        args.push("--draft".into());
    }

    for label in &config.pr.labels {
        args.push("--label".into());
        args.push(label.clone());
    }

    let output = Command::new("gh")
        .args(&args)
        .output()?;

    if output.status.success() {
        let url = String::from_utf8_lossy(&output.stdout).trim().to_string();
        Ok(StepResult {
            name: "PR".into(),
            status: StepStatus::Pass,
            duration: start.elapsed(),
            output: Some(url),
        })
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        Ok(StepResult {
            name: "PR".into(),
            status: StepStatus::Fail(format!("PR creation failed: {stderr}")),
            duration: start.elapsed(),
            output: None,
        })
    }
}

fn build_pr_title(config: &Config) -> String {
    let version = std::fs::read_to_string("VERSION")
        .unwrap_or_default()
        .trim()
        .to_string();

    if version.is_empty() {
        format!("ship: release {}", config.project_name())
    } else {
        format!("ship: {} v{}", config.project_name(), version)
    }
}

fn build_pr_body(config: &Config, steps: &[StepResult]) -> String {
    let mut body = String::from("## Summary\n\n");

    // Collect step results
    for step in steps {
        let icon = match &step.status {
            StepStatus::Pass => "✅",
            StepStatus::Fail(_) => "❌",
            StepStatus::Warn(_) => "⚠️",
            StepStatus::Skip(_) => "⏭️",
        };

        let detail = match &step.status {
            StepStatus::Pass => step.output.as_deref().unwrap_or("passed"),
            StepStatus::Fail(msg) => msg.as_str(),
            StepStatus::Warn(msg) => msg.as_str(),
            StepStatus::Skip(msg) => msg.as_str(),
        };

        body.push_str(&format!("- {icon} **{}**: {detail}\n", step.name));
    }

    body.push_str("\n## Test Plan\n\n");
    body.push_str("- [ ] Verify on staging\n");
    body.push_str("- [ ] Check production after deploy\n");

    body.push_str(&format!(
        "\n---\nGenerated by [ship](https://github.com/aspelldenny/ship) for **{}**\n",
        config.project_name()
    ));

    body
}
